// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransServiceClient is the client API for TransService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransServiceClient interface {
	TransIn(ctx context.Context, in *TransInReq, opts ...grpc.CallOption) (*TransInReply, error)
	TransOut(ctx context.Context, in *TransOutReq, opts ...grpc.CallOption) (*TransOutReply, error)
}

type transServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransServiceClient(cc grpc.ClientConnInterface) TransServiceClient {
	return &transServiceClient{cc}
}

func (c *transServiceClient) TransIn(ctx context.Context, in *TransInReq, opts ...grpc.CallOption) (*TransInReply, error) {
	out := new(TransInReply)
	err := c.cc.Invoke(ctx, "/dt.pb.TransService/TransIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transServiceClient) TransOut(ctx context.Context, in *TransOutReq, opts ...grpc.CallOption) (*TransOutReply, error) {
	out := new(TransOutReply)
	err := c.cc.Invoke(ctx, "/dt.pb.TransService/TransOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransServiceServer is the server API for TransService service.
// All implementations must embed UnimplementedTransServiceServer
// for forward compatibility
type TransServiceServer interface {
	TransIn(context.Context, *TransInReq) (*TransInReply, error)
	TransOut(context.Context, *TransOutReq) (*TransOutReply, error)
	mustEmbedUnimplementedTransServiceServer()
}

// UnimplementedTransServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransServiceServer struct {
}

func (UnimplementedTransServiceServer) TransIn(context.Context, *TransInReq) (*TransInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransIn not implemented")
}
func (UnimplementedTransServiceServer) TransOut(context.Context, *TransOutReq) (*TransOutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransOut not implemented")
}
func (UnimplementedTransServiceServer) mustEmbedUnimplementedTransServiceServer() {}

// UnsafeTransServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransServiceServer will
// result in compilation errors.
type UnsafeTransServiceServer interface {
	mustEmbedUnimplementedTransServiceServer()
}

func RegisterTransServiceServer(s grpc.ServiceRegistrar, srv TransServiceServer) {
	s.RegisterService(&TransService_ServiceDesc, srv)
}

func _TransService_TransIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransServiceServer).TransIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dt.pb.TransService/TransIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransServiceServer).TransIn(ctx, req.(*TransInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransService_TransOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransOutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransServiceServer).TransOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dt.pb.TransService/TransOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransServiceServer).TransOut(ctx, req.(*TransOutReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TransService_ServiceDesc is the grpc.ServiceDesc for TransService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dt.pb.TransService",
	HandlerType: (*TransServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransIn",
			Handler:    _TransService_TransIn_Handler,
		},
		{
			MethodName: "TransOut",
			Handler:    _TransService_TransOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
